spring.application.name=demopg
spring.application.name=SpringBootSecurityPostgresqlApplication
# spring.datasource.url=jdbc:mysql//localhost::3306/testdb_apring?useSSL=false
spring.datasource.url =jdbc:postgresql://localhost:5452/user_api?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=alexa
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
